### ISSUE TITLE
aggregate data sources into a unified Plains Cree lexical database

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/crk-db#1]
This is a meta-issue for tracking initial aggregation of the current dictionary data sources. Other sources may be added later, but this issue can be considered complete once the following issues are done, and we have an initial aggregation process and ALTLab-specific database in place.

# To Do

- [ ] integrate Arok Wolvengrey's _Cree Words_ (#9)
- [ ] integrate Maskwacîs dictionary (#5)
- [ ] convert / prepare database for _itwêwina_ (#10)

# Notes

(See also these [Database Specification Notes](https://docs.google.com/document/d/1uBJtG8WxRbUIBSdeNBynksKQoRImXJoCbEVFcW9HIJw/edit) on Google Drive.)

Reviewing a small number of differences between a version of CW from this January and from 2014, I'm starting to more and more think whether the manual evaluation of CW vs. MD content is realistic, given that AEW is updating CW continuously, and MD content will be expanded as well with the "new" words collected in the recordings.

In principle, we'd need to run through every new version of CW, and then figure out which CW entries have changed or are new ones, and then somehow automatically contrast these with the entire content of MD as to whether some CW entries might have substantial semantic overlap with MD. Only when the English words in the definitions are exactly the same, or when the English words of one definition are a complete subset of the English words in the other dictionary could we automatically decide that the entries in the two dictionaries can be "merged". In all other cases, this would need to be assessed manually by a linguist. E.g. we know of some dictionary entries that concern the same sense, but do not have practically any overlap in their definitions, for instance:

MD: mêscihew <- meschihew       ᒣᐢᒋᐦᐁᐤ  vp      He kills them all, wipes them out.
CW: mêscihew <- s/he kills s.o. off, s/he annihilates s.o., s/he exterminates s.o. (VTA-1)

An alternative is that 1) we base matching dictionary entries from multiple sources based on the assumption that the combination of the dictionary entry head and the inflectional category is unique in all sources, so can be used to map 1:1 potentially similar dictionary entries; and 2) we merge dictionary entries from multiple sources only when that can be done automatically, i.e. when the content words in the English definitions overlap completely (or almost completely), i.e. the English content words in one source can all be found in the dictionary entry in the other source, and vice versa.

Thus, we leave the manual assessment of sense similarity until later. But in the interim, what we need to do in any event, also as a necessary step for eventual manual assessment, is a) the standardization of the orthographical form of the lexical entries in non-CW sources, b) the assignment of inflectional category for all dictionary entries, and c) the assignment of the stem for all dictionary entries (at least those not in CW).

This strategy would allow us to aggregate not only MD but also AECD. In the case of three sources, the merging consideration would be applied pairwise, in that it might be that the English definitions of only two sources are practically identical, but a third source might have narrower or broader definitions.

**Comment by dwhieb** [comment]
[Database Specification Notes](https://docs.google.com/document/d/1uBJtG8WxRbUIBSdeNBynksKQoRImXJoCbEVFcW9HIJw/edit)
